### ISSUE TITLE
Missing variable in 'new' method

### ISSUE THREAD

**Issue by brainwins** [turingschool/curriculum#1231]
On I1: Form-based Workflow, Creating the NEW Action and View
It says to create the method #new. But it's empty. Where I'm pretty sure it has to have
`@article = Article.new`
inside.

![new](https://cloud.githubusercontent.com/assets/10680518/23284622/146c6f90-f9f2-11e6-96df-6bedc89cdeb1.jpg)

**Comment by Carmer** [comment]
👍
