### ISSUE TITLE
Receiving errors even when I copy-paste code from the sample

### ISSUE THREAD

**Issue by ianalexh** [turingschool/curriculum#537]
http://tutorials.jumpstartlab.com/projects/eventmanager.html

Hello,

I'm pretty new to coding and to Ruby, so this may be very obvious.

I've got this much code now, and the problems started appearing when I added "header_converters: :symbol"

require "csv"
puts "EventManager initialized."

contents = CSV.open "event_attendees.csv", headers: true, header_converters: :symbol
contents.each do |row|
  name = row[:first_name]
  zipcode = row[:zipcode]
  puts "#{name} #{zipcode}"
end

I continue to get errors when I get to the correct directory in the Terminal and type "ruby event_manager.rb"

I'm running Mac OSX 10.8, Mountain Lion, with Ruby 2.0.0

Any pointers would be greatly appreciated! Errors below.

EventManager initialized.
/Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:994:in `block in <class:CSV>': undefined method`encode' for nil:NilClass (NoMethodError)
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2168:in `[]'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2168:in`block (2 levels) in convert_fields'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2166:in `each'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2166:in`block in convert_fields'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2165:in `map'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2165:in`with_index'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2165:in `convert_fields'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:2206:in`parse_headers'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:1882:in `block in shift'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:1774:in`loop'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:1774:in `shift'
    from /Users/apple/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/csv.rb:1716:in`each'
    from event_manager.rb:5:in `<main>'
Apples-MacBook-Pro:lib apple$

**Comment by AhmedNadar** [comment]
I was in a similar situation; when I use `contents = CSV.open "languages.csv", headers: true, header_converters: :symbol` I got this error: `undefined method 'encode' for nil:NilClass (NoMethodError)`. It's complaining about `header_converter: :symbol` method. 

After reviewing "languages.csv" file I found it's header starts with " " a space. Removing that space solved that issue.
