### ISSUE TITLE
Blogger 2 - NoMethodError on Tag creation via rails console

### ISSUE THREAD

**Issue by tschale** [turingschool/curriculum#870]
###### 

EDIT:
My bad, I switched ruby-versions from 2.2.0dev to 2.1.1 and it works without error!
###### 

I'm doing the Blogger 2 Tutorial and ran into an issue in the Tagging section. I created the models, just as in the tutorial, but when I try to create a new tag on the rails console with _a.tags.create name: "tag1"_, I get an _NoMethodError: undefined method `name' for nil:NilClass_. It seems to be inserted into the tags and taggings tables, but right after that there is a rollback and the aforementioned error...

**Comment by Zibilyonik** [comment]
Thanks for the solution mate, saved me a lot of trouble!

**Comment by tschale** [comment]
Awesome! But I think we can close this one :)

**Comment by didymus707** [comment]
I am still confused about the solution. What is the solution, I'm a total noob here pls

**Comment by tschale** [comment]
Well back then I switched back ruby versions. But this was 6 years ago, not sure if you're on the right track here...

**Comment by Zibilyonik** [comment]
I've used ruby version controller to change the ruby version from a newer
version to an older one to solve the issue. I can record and send you a
screen recording of the process if you'd like.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by didymus707** [comment]
@Zibilyonik thanks man, I got it figured out
